spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/liquibase-outputChangeLog.xml
  datasource:
    url: jdbc:mysql://localhost:3306/blogengine?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234567890
  jpa:
    hibernate:
      ddl-auto: update

upload:
  path: src/main/resources/uploads/

server:
  port: ${PORT:8080}


mail:
  host: smtp.yandex.ru
  username: archipenkov@tut.by
  password:
  port: 25
  protocol: smtps
  debug: true