spring:
  mail:
    host: smtp.yandex.ru
    username: blogmanager2022@yandex.ru
    password: qwerty123456zxcvb
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/liquibase-outputChangeLog.xml
  datasource:
    url: jdbc:mysql://localhost:3306/blogengine?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234567890
  jpa:
    hibernate:
      ddl-auto: update

upload:
  path: src/main/resources/uploads/



