spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/liquibase-outputChangeLog.xml
  datasource:
    url: jdbc:mysql://localhost:3306/blogengine?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234567890
  jpa:
    hibernate:
      ddl-auto: none

